### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by anthrotype** [google/brotli-wheels#12]
The stable release of Python 3.9 was released last week.
We need to build wheels for 3.9 as well.
I think it should be enough to simply add 3.9 to the build matrix of both Travis and Appveyor, after having updated the multibuild submodule to the latest "devel" branch which should support 3.9 now.
We could also drop support for 3.5 since it has reached EOL.

**Comment by anthrotype** [comment]
Looks like Appveyor still hasn't added support for Python 3.9 
https://github.com/appveyor/ci/issues/3541

**Comment by ajkaijanaho** [comment]
> Looks like Appveyor still hasn't added support for Python 3.9
> [appveyor/ci#3541](https://github.com/appveyor/ci/issues/3541)

That ticket is closed by now. Any updates?

**Comment by anthrotype** [comment]
Thanks for the reminder. The python3.9 wheels for Windows are currently missing from PyPI https://pypi.org/project/Brotli/1.0.9/#files

I have just pushed an empty commit to trigger a new build on Appveyor, if that passes (as it should now) I will upload the generated wheels as well. Stay tuned.

**Comment by anthrotype** [comment]
Appveyor python3.9 build passed successfully:
https://ci.appveyor.com/project/szabadka/brotli-wheels/builds/37118320

The files Brotli-1.0.9-cp39-cp39-win32.whl and Brotli-1.0.9-cp39-cp39-win_amd64.whl have been uploaded to https://pypi.org/project/Brotli/1.0.9/#files
